# Generated by Django 6.0.5 on 2026-06-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('home', 'Home'), ('reflexao', 'Reflexão do Dia'), ('biblia', 'Bíblia'), ('noite', 'Palavra da Noite')], help_text='Identificador único para buscar a imagem correta no frontend.', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Título interno para organização.', max_length=100)),
                ('image', models.ImageField(help_text='Imagem do screenshot.', upload_to='landing/')),
                ('alt_text', models.CharField(blank=True, help_text='Texto alternativo para acessibilidade.', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Define se a imagem será enviada para o frontend.')),
                ('sort_order', models.IntegerField(default=0, help_text='Ordem de exibição (opcional, já que a busca é por key).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Screenshot da Landing Page',
                'verbose_name_plural': 'Screenshots da Landing Page',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
