# Generated by Django 6.0.5 on 2026-07-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='E-mail do lead.', max_length=254, unique=True)),
                ('name', models.CharField(blank=True, help_text='Nome do lead (opcional).', max_length=150)),
                ('source', models.CharField(default='Tudo Parece Pesado', help_text='Origem da captura ou material entregue.', max_length=100)),
                ('consent_given', models.BooleanField(default=False, help_text='Consentimento para receber comunicações.')),
                ('utm_source', models.CharField(blank=True, help_text='UTM Source', max_length=100)),
                ('utm_medium', models.CharField(blank=True, help_text='UTM Medium', max_length=100)),
                ('utm_campaign', models.CharField(blank=True, help_text='UTM Campaign', max_length=100)),
                ('utm_content', models.CharField(blank=True, help_text='UTM Content', max_length=100)),
                ('utm_term', models.CharField(blank=True, help_text='UTM Term', max_length=100)),
                ('brevo_sync_status', models.BooleanField(default=False, help_text='Status de sincronização com o Brevo.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
