# Generated by Django 6.0.5 on 2026-05-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='preferred_time',
            field=models.CharField(choices=[('morning', 'Manhã'), ('evening', 'Noite'), ('any', 'Qualquer momento')], default='morning', max_length=20),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='timezone',
            field=models.CharField(default='America/Sao_Paulo', max_length=100),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
