# Generated by Django 6.0.5 on 2026-05-09 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('title', models.CharField(max_length=180)),
                ('scripture_reference', models.CharField(max_length=150)),
                ('scripture_text', models.TextField()),
                ('reflection_body', models.TextField()),
                ('guiding_question', models.TextField()),
                ('closing_prayer', models.TextField()),
                ('ai_generated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserReflectionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reflection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='reflection.dailyreflection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'reflection')},
            },
        ),
    ]
