# Generated by Django 6.0.5 on 2026-05-13 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0003_biblepassage_passageexplanation_passage'),
        ('reflection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreflection',
            name='passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reflections', to='bible.biblepassage'),
        ),
    ]
