# Generated by Django 6.0.5 on 2026-05-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflection', '0002_dailyreflection_passage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreflection',
            name='share_quote',
            field=models.TextField(blank=True, default=''),
        ),
    ]
