# Generated by Django 6.0.5 on 2026-05-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflection', '0003_dailyreflection_share_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreflection',
            name='emotional_theme',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dailyreflection',
            name='theme_key',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
