# Generated by Django 6.0.5 on 2026-05-24 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotional', '0005_auto_20260523_2054'),
        ('reflection', '0004_dailyreflection_emotional_theme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContemplativeExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('experience_type', models.CharField(choices=[('audio_reflection', 'Meditação em Áudio'), ('guided_prayer', 'Oração Guada'), ('spiritual_path', 'Trilha de Silêncio')], max_length=30)),
                ('audio_url', models.CharField(blank=True, default='', max_length=255)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpiritualCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('theme_key', models.CharField(blank=True, default='', max_length=50)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EditorialFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.TextField()),
                ('fragment_type', models.CharField(choices=[('quote', 'Assinatura Poética'), ('prayer', 'Oração Breve'), ('scripture', 'Fragmento Bíblico'), ('question', 'Pergunta Guia')], default='quote', max_length=20)),
                ('theme_key', models.CharField(blank=True, default='', max_length=50)),
                ('share_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('devotional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='devotional.devotionalcontent')),
                ('reflection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='reflection.dailyreflection')),
            ],
        ),
    ]
