# Generated by Django 6.0.5 on 2026-05-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflection', '0005_contemplativeexperience_spiritualcollection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreflection',
            name='night_prayer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dailyreflection',
            name='night_word',
            field=models.TextField(blank=True, default=''),
        ),
    ]
