# Generated by Django on 2026-05-30

from django.db import migrations
from difflib import SequenceMatcher

def get_similarity(a: str, b: str) -> float:
    if not a or not b: return 0.0
    return SequenceMatcher(None, a, b).ratio()

def apply_night_similarity_fixes(apps, schema_editor):
    DailyReflection = apps.get_model('reflection', 'DailyReflection')
    
    for reflection in DailyReflection.objects.all():
        updated = False
        
        night_word = reflection.night_word or ""
        night_prayer = reflection.night_prayer or ""
        share_quote = reflection.share_quote or ""
        reflection_body = reflection.reflection_body or ""
        closing_prayer = reflection.closing_prayer or ""
        title = reflection.title or ""
        
        clean_night_word = night_word.strip().lower()
        clean_share_quote = share_quote.strip().lower()
        clean_reflection = reflection_body.strip().lower()
        clean_title = title.strip().lower()
        
        similarity_with_quote = get_similarity(clean_night_word, clean_share_quote)
        similarity_with_body = get_similarity(clean_night_word, clean_reflection)
        
        is_empty = clean_night_word == ""
        is_literal = (clean_night_word in clean_reflection) or (clean_night_word in clean_share_quote) or (clean_night_word in clean_title)
        is_similar_quote = similarity_with_quote >= 0.45
        is_similar_body = similarity_with_body >= 0.55
        
        if is_empty or is_literal or is_similar_quote or is_similar_body:
            reflection.night_word = "Há um repouso silencioso que nos aguarda no fim de tudo."
            updated = True
            
        clean_night_prayer = night_prayer.strip().lower()
        clean_closing_prayer = closing_prayer.strip().lower()
        similarity_prayer = get_similarity(clean_night_prayer, clean_closing_prayer)
        
        if similarity_prayer >= 0.50 or clean_night_prayer == "":
            reflection.night_prayer = "Senhor, entrego este dia em tuas mãos. Que a noite traga repouso e a certeza de que não estou só. Amém."
            updated = True
            
        if updated:
            reflection.save(update_fields=['night_word', 'night_prayer'])

def reverse_similarity_fixes(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('reflection', '0006_dailyreflection_night_prayer_and_more'),
    ]

    operations = [
        migrations.RunPython(apply_night_similarity_fixes, reverse_similarity_fixes),
    ]
