# Generated by Django 6.0.5 on 2026-06-24 03:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflection', '0007_backfill_night_similarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreflection',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
