# Generated by Django 6.0.5 on 2026-06-24 03:16

import uuid
from django.db import migrations

def gen_uuid(apps, schema_editor):
    DailyReflection = apps.get_model('reflection', 'DailyReflection')
    for row in DailyReflection.objects.all():
        row.public_id = uuid.uuid4()
        row.save(update_fields=['public_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('reflection', '0008_dailyreflection_public_id'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
