# Generated by Django 6.0.5 on 2026-06-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflection', '0010_alter_dailyreflection_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreflection',
            name='share_bg_image',
            field=models.CharField(blank=True, default='gradient_light', help_text='Chave do fundo da imagem (ex: rain_glass, coffee_table)', max_length=50),
        ),
        migrations.AddField(
            model_name='dailyreflection',
            name='share_text',
            field=models.CharField(blank=True, default='', help_text='Frase pastoral curta para repost. Máx 110 caracteres.', max_length=110),
        ),
    ]
