# Generated by Django 6.0.5 on 2026-06-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflection', '0012_alter_dailyreflection_share_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreflection',
            name='daily_companion',
            field=models.TextField(blank=True, default='', help_text='A Palavra Continua: Ponte delicada de acompanhamento para as próximas horas.'),
        ),
        migrations.AddField(
            model_name='dailyreflection',
            name='main_truth',
            field=models.TextField(blank=True, default='', help_text='O Fio da Palavra: A verdade central destilada que permanece.'),
        ),
    ]
