# Generated by Django 6.0.5 on 2026-05-09 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='DevotionalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('scripture_reference', models.CharField(max_length=150)),
                ('scripture_text', models.TextField()),
                ('reflection', models.TextField()),
                ('prayer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devotionals', to='devotional.emotion')),
            ],
        ),
        migrations.CreateModel(
            name='UserDevotional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessed_by', to='devotional.devotionalcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devotional_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
