# Generated by Django 6.0.5 on 2026-05-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotional', '0002_devotionalcontent_passage'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotionalcontent',
            name='guiding_question',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='devotionalcontent',
            name='practical_application',
            field=models.TextField(blank=True),
        ),
    ]
