# Generated by Django 6.0.5 on 2026-05-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotional', '0003_devotionalcontent_guiding_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotionalcontent',
            name='emotional_theme',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='devotionalcontent',
            name='reviewed_by_human',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devotionalcontent',
            name='share_quote',
            field=models.TextField(blank=True, default=''),
        ),
    ]
