# Generated by Django 6.0.5 on 2026-05-23 23:54

from django.db import migrations

def populate_emotions_and_devotionals(apps, schema_editor):
    import sys
    from django.conf import settings
    
    # Se estiver rodando a suíte de testes do Django, pulamos todo o seed (emoções e devocionais)
    # para evitar quebrar asserções de testes existentes que exigem banco vazio ou contagens específicas,
    # bem como conflitos de UNIQUE constraint no slug já que os testes criam suas próprias emoções em setUp().
    if 'test' in sys.argv or getattr(settings, 'TESTING', False):
        return

    Emotion = apps.get_model('devotional', 'Emotion')
    BiblePassage = apps.get_model('bible', 'BiblePassage')
    DevotionalContent = apps.get_model('devotional', 'DevotionalContent')
    
    from services.bible.normalization import NormalizationService
    
    emotions_data = [
        {"id": 1, "name": "Ansioso", "slug": "ansioso", "icon": "anxiety_icon"},
        {"id": 2, "name": "Triste", "slug": "triste", "icon": "sad_icon"},
        {"id": 3, "name": "Medo", "slug": "medo", "icon": "fear_icon"},
        {"id": 4, "name": "Desmotivado", "slug": "desmotivado", "icon": "unmotivated_icon"},
        {"id": 5, "name": "Sozinho", "slug": "sozinho", "icon": "lonely_icon"},
        {"id": 6, "name": "Sem Esperança", "slug": "sem-esperanca", "icon": "hopeless_icon"},
        {"id": 7, "name": "Direção", "slug": "direcao", "icon": "direction_icon"},
        {"id": 8, "name": "Gratidão", "slug": "gratidao", "icon": "gratitude_icon"},
        {"id": 9, "name": "Corajoso, mas incerto", "slug": "corajoso-mas-incerto", "icon": "courageous_uncertain_icon"},
        {"id": 10, "name": "Chamado, mas hesitante", "slug": "chamado-mas-hesitante", "icon": "called_hesitant_icon"},
        {"id": 11, "name": "Tentado", "slug": "tentado", "icon": "tempted_icon"},
        {"id": 12, "name": "Em conflito com alguém", "slug": "em-conflito-com-alguem", "icon": "conflict_icon"},
        {"id": 13, "name": "Grato, mas disperso", "slug": "grato-mas-disperso", "icon": "grateful_dispersed_icon"},
        {"id": 14, "name": "Disciplinado, mas frio", "slug": "disciplinado-mas-frio", "icon": "disciplined_cold_icon"},
    ]
    
    # 1. Update/Create all 14 emotions
    emotions_map = {}
    for emo_data in emotions_data:
        emotion_obj, _ = Emotion.objects.update_or_create(
            id=emo_data["id"],
            defaults={
                "name": emo_data["name"],
                "slug": emo_data["slug"],
                "icon": emo_data["icon"]
            }
        )
        emotions_map[emo_data["slug"]] = emotion_obj


    # 2. Feed the 12 new devotionals
    devotionals_data = [
        # corajoso-mas-incerto

        {
            "slug": "corajoso-mas-incerto",
            "title": "A obediência dá o primeiro passo",
            "scripture_reference": "Josué 1:9",
            "scripture_text": "Não fui eu que ordenei a você? Seja forte e corajoso! Não se apavore nem desanime, pois o Senhor, o seu Deus, estará com você por onde você andar.",
            "reflection": "O medo raramente desaparece antes da ação. Josué não recebeu a promessa de que não sentiria tremor, mas sim de que Deus caminharia com ele. A coragem cristã não é uma virtude de heróis que não temem; é a obediência simples de quem dá o primeiro passo na direção correta, mesmo com a voz embargada e as pernas fracas.",
            "prayer": "Senhor, não espero o medo passar para obedecer-te. Que eu dê o pequeno passo de hoje confiando que a Tua presença sustenta os meus pés na incerteza.",
            "share_quote": "A coragem cristã não é uma virtude de heróis que não temem; é a obediência simples de quem dá o primeiro passo."
        },
        {
            "slug": "corajoso-mas-incerto",
            "title": "Firmeza na fraqueza",
            "scripture_reference": "2 Timóteo 1:7",
            "scripture_text": "Pois Deus não nos deu espírito de covardia, mas de poder, de amor e de equilíbrio.",
            "reflection": "A covardia paralisa e nos faz retroceder. Mas o equilíbrio que Deus dá nos permite enxergar a realidade sem sermos dominados por ela. A firmeza não vem de nossa força interior, mas do Espírito que nos lembra de que fomos reconciliados e amados.",
            "prayer": "Senhor, retira-me do casulo da covardia. Que eu enfrente as decisões desta tarde com o equilíbrio e o amor que só o Teu Espírito concede.",
            "share_quote": "A firmeza não vem de nossa força interior, mas do Espírito que nos lembra de que fomos reconciliados e amados."
        },
        # chamado-mas-hesitante
        {
            "slug": "chamado-mas-hesitante",
            "title": "Quem sou eu diante do chamado",
            "scripture_reference": "Êxodo 3:11-12",
            "scripture_text": "Mas Moisés perguntou a Deus: 'Quem sou eu para apresentar-me ao faraó e tirar os israelitas do Egito?'. Deus respondeu: 'Eu estarei com você. Esta será a prova de que sou eu quem o envia: quando você tirar o povo do Egito, vocês prestarão culto a Deus neste monte'.",
            "reflection": "Moisés olhou para a própria incapacidade e hesitou. É a reação natural de quem percebe a gravidade da vocação. A resposta de Deus, porém, não foi uma palestra motivacional sobre o potencial de Moisés, mas uma afirmação simples sobre a Sua própria presença: 'Eu estarei com você'. O chamado é sobre Quem envia, não sobre quem vai.",
            "prayer": "Senhor, perdoa minha hesitação diante do que me pedes. Que eu pare de buscar em mim as qualificações que só a Tua presença pode suprir no caminho comum.",
            "share_quote": "O chamado é sobre Quem envia, não sobre quem vai."
        },
        {
            "slug": "chamado-mas-hesitante",
            "title": "O jovem que não precisa temer",
            "scripture_reference": "Jeremias 1:6-8",
            "scripture_text": "Ah, Senhor Deus!, eu disse. Eu não sei falar, pois sou apenas um jovem. Mas o Senhor me respondeu: Não diga: 'Sou apenas um jovem'. Você irá a todos a quem eu o enviar e dirá tudo o que eu ordenar. Não tenha medo deles, pois estou com você para protegê-lo, diz o Senhor.",
            "reflection": "A desculpa da juventude ou da fragilidade é um refúgio conveniente para evitar o custo da obediência. Deus confronta Jeremias com carinho e firmeza: a boca do profeta dirá apenas o que o Senhor ordenar, e sua segurança virá do resguardo divino. O temor diminui à medida que a autoridade de Deus assume o controle.",
            "prayer": "Senhor, afasta minhas desculpas convenientes. Conduz meus passos e minhas palavras hoje, mesmo nos ambientes em que me sinto incapaz e menor.",
            "share_quote": "A desculpa da juventude ou da fragilidade é um refúgio conveniente para evitar o custo da obediência."
        },
        # tentado
        {
            "slug": "tentado",
            "title": "O limite e o escape",
            "scripture_reference": "1 Coríntios 10:13",
            "scripture_text": "Não sobreveio a vocês nenhuma tentação que não fosse comum aos homens. E Deus é fiel; ele não permitirá que vocês sejam tentados além do que podem suportar. Mas, quando forem tentados, ele lhes providenciará um escape, para que o possam suportar.",
            "reflection": "A tentação promete um alívio rápido e privado, mas cobra um preço de longo prazo na alma. Paulo nos lembra de que não estamos diante de uma luta sobre-humana e que Deus é fiel para garantir um escape. A fidelidade acontece no intervalo discreto entre o impulso do desejo e a decisão da escolha.",
            "prayer": "Senhor, abre meus olhos para enxergar o escape que já providenciaste na tentação de hoje. Que eu escolha a Tua fidelidade em vez do alívio ilusório.",
            "share_quote": "A fidelidade acontece no intervalo discreto entre o impulso do desejo e a decisão da escolha."
        },
        {
            "slug": "tentado",
            "title": "A sujeição que liberta",
            "scripture_reference": "Tiago 4:7",
            "scripture_text": "Portanto, submetam-se a Deus. Resistam ao Diabo, e ele fugirá de vocês.",
            "reflection": "Resistir sem se submeter é um esforço heroico e inútil que gera apenas cansaço e frustração. A verdadeira vitória sobre a tentação começa de joelhos, na sujeição voluntária e silenciosa à soberania e ao amor de Deus. Só a partir dessa rendição temos autoridade para resistir.",
            "prayer": "Senhor, eu me rendo novamente ao Teu senhorio. Que a minha resistência à tentação seja o fruto natural da minha sujeição à Tua graça acolhedora.",
            "share_quote": "A verdadeira vitória sobre a tentação começa de joelhos, na sujeição voluntária e silenciosa à soberania e ao amor de Deus."
        },
        # em-conflito-com-alguem
        {
            "slug": "em-conflito-com-alguem",
            "title": "O perdão que liberta a memória",
            "scripture_reference": "Colossenses 3:13",
            "scripture_text": "Suportem-se uns aos outros e perdoem-se mutuamente, caso alguém tenha motivo de queixa contra outro. Perdoem como o Senhor lhes perdoou.",
            "reflection": "O perdão não é um sentimento caloroso que surge espontaneamente; é uma decisão de obediência e graça. Perdoar não significa apagar a ferida, mas sim retirar da dor o direito de ditar o nosso amanhã. Suportar o outro na sua fraqueza é o eco prático do quanto fomos suportados por Deus.",
            "prayer": "Senhor, ajuda-me a desatar o nó da mágoa em meu coração. Perdoo quem me feriu, não por merecimento deles, mas porque a Tua graça me alcançou primeiro.",
            "share_quote": "Perdoar não significa apagar a ferida, mas sim retirar da dor o direito de ditar o nosso amanhã."
        },
        {
            "slug": "em-conflito-com-alguem",
            "title": "Deixar a oferta no altar",
            "scripture_reference": "Mateus 5:23-24",
            "scripture_text": "Portanto, se você estiver apresentando a sua oferta no altar e ali se lembrar de que seu irmão tem alguma coisa contra você, deixe a sua oferta ali diante do altar e vá primeiro reconciliar-se com o seu irmão; depois volte e apresente a sua oferta.",
            "reflection": "Jesus estabelece uma ligação indissolúvel entre a nossa adoração a Deus e a nossa reconciliação com o outro. É fácil esconder o orgulho espiritual atrás de rituais religiosos impecáveis. A verdadeira adoração, porém, exige o esforço honesto de restabelecer a paz e a verdade nos relacionamentos rompidos.",
            "prayer": "Senhor, que eu não use a espiritualidade como disfarce para fugir de conversas difíceis. Dá-me coragem para buscar a paz e a reconciliação hoje.",
            "share_quote": "A verdadeira adoração exige o esforço honesto de restabelecer a paz e a verdade nos relacionamentos rompidos."
        },
        # grato-mas-disperso
        {
            "slug": "grato-mas-disperso",
            "title": "Atenção contra a pressa",
            "scripture_reference": "Salmos 103:2",
            "scripture_text": "Bendiga o Senhor a minha alma, e não se esqueça de nenhum de seus benefícios.",
            "reflection": "A pressa do cotidiano é uma das maiores inimigas da espiritualidade contemplativa. A alma dispersa olha para tantas coisas que acaba esquecendo o essencial: a bondade persistente do Doador. Lembrar dos benefícios de Deus exige pausa, atenção concentrada e o cultivo intencional da memória espiritual.",
            "prayer": "Senhor, acalma a pressa em meu coração. Que eu pare um instante agora para lembrar da Tua fidelidade e agradecer por aquilo que a pressa costuma ignorar.",
            "share_quote": "A pressa do cotidiano é uma das maiores inimigas da espiritualidade contemplativa."
        },
        {
            "slug": "grato-mas-disperso",
            "title": "O eco da gratidão",
            "scripture_reference": "1 Tessalonicenses 5:16-18",
            "scripture_text": "Alegrem-se sempre. Orem continuamente. Deem graças em todas as circunstâncias, pois esta é a vontade de Deus para vocês em Cristo Jesus.",
            "reflection": "Dar graças em todas as circunstâncias não é uma exigência de otimismo ingênuo, mas uma postura teológica profunda. Significa crer que, mesmo nos dias nublados e confusos, a bondade de Deus permanece activa. A gratidão é o fio invisível que nos conecta à presença divina na dispersão do mundo.",
            "prayer": "Senhor, dou-Te graças pela quietude invisível que sustenta a minha vida. Que o meu coração aprenda a repousar na certeza de que Tu controlas tudo.",
            "share_quote": "A gratidão é o fio invisível que nos conecta à presença divina na dispersão do mundo."
        },
        # disciplinado-mas-frio
        {
            "slug": "disciplinado-mas-frio",
            "title": "O regresso ao primeiro amor",
            "scripture_reference": "Apocalipse 2:4-5",
            "scripture_text": "Contra você, porém, tenho isto: você abandonou o seu primeiro amor. Lembre-se de onde caiu! Arrependa-se e pratique as obras que praticava no princípio.",
            "reflection": "A rotina espiritual pode ser perfeitamente disciplinada e, ao mesmo tempo, vazia de afeição sincera. Hábitos saudáveis correm o risco de se tornarem mecanismos de autojustificação ou mera obrigação fria. Deus nos convida a lembrar da doçura e do temor do início, arrependendo-nos do formalismo vazio.",
            "prayer": "Senhor, perdoa a rigidez fria das minhas práticas espirituais. Devolve-me o amor simples e a alegria da Tua presença que outrora me moviam.",
            "share_quote": "A rotina espiritual pode ser perfeitamente disciplinada e, ao mesmo tempo, vazia de afeição sincera."
        },
        {
            "slug": "disciplinado-mas-frio",
            "title": "A videira e os ramos",
            "scripture_reference": "João 15:4-5",
            "scripture_text": "Permaneçam em mim, e eu permanecerei em vocês. Nenhum ramo pode dar fruto por si mesmo, se não permanecer na videira. Vocês também não podem dar fruto, se não permanecerem em mim.",
            "reflection": "A nossa produtividade ou perfeição nas disciplinas espirituais de nada serve se faltar a conexão íntima e vital com Cristo. O ramo não faz esforço para produzir fruto de forma performática; ele simplesmente permanece ligado ao tronco e recebe a seiva. Permanecer é uma postura de descanso e dependência.",
            "prayer": "Senhor, não quero apenas executar rituais corretos. Quero permanecer em Ti, recebendo a Tua vida e deixando que a Tua graça produza frutos espontâneos em mim.",
            "share_quote": "Permanecer é uma postura de descanso e dependência."
        }
    ]

    for item in devotionals_data:
        emotion_obj = emotions_map[item["slug"]]
        
        # 1. Resolve BiblePassage
        can_id, book, chap, verses = NormalizationService.normalize(item["scripture_reference"])
        passage_obj, _ = BiblePassage.objects.get_or_create(
            canonical_id=can_id,
            defaults={
                "book_name": book,
                "chapter": chap,
                "verses": verses or "",
                "text_original": item["scripture_text"],
                "translation": "NVI",
                "language": "pt"
            }
        )
        
        # 2. Update/Create DevotionalContent
        DevotionalContent.objects.get_or_create(
            emotion=emotion_obj,
            title=item["title"],
            defaults={
                "passage": passage_obj,
                "scripture_reference": item["scripture_reference"],
                "scripture_text": item["scripture_text"],
                "reflection": item["reflection"],
                "prayer": item["prayer"],
                "share_quote": item["share_quote"],
                "reviewed_by_human": True,
                "is_active": True,
                "ai_generated": False
            }
        )

def remove_emotions_and_devotionals(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('devotional', '0004_devotionalcontent_emotional_theme_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_emotions_and_devotionals, reverse_code=remove_emotions_and_devotionals)
    ]

