# Generated by Django 6.0.5 on 2026-06-24 03:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotional', '0005_auto_20260523_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotionalcontent',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
