# Generated by Django 6.0.5 on 2026-06-24 03:13

import uuid
from django.db import migrations

def gen_uuid(apps, schema_editor):
    DevotionalContent = apps.get_model('devotional', 'DevotionalContent')
    for row in DevotionalContent.objects.all():
        row.public_id = uuid.uuid4()
        row.save(update_fields=['public_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('devotional', '0006_devotionalcontent_public_id'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
