# Generated by Django 6.0.5 on 2026-06-24 03:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotional', '0007_populate_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotionalcontent',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
