# Generated by Django 6.0.5 on 2026-06-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotional', '0009_devotionalcontent_share_bg_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotionalcontent',
            name='share_bg_image',
            field=models.CharField(blank=True, choices=[('gradient_light', 'Fundo padrão claro'), ('gradient_dark', 'Fundo padrão escuro'), ('window_light', 'Luz da janela'), ('coffee_table', 'Mesa com café')], default='gradient_light', help_text='Selecione o fundo da imagem de compartilhamento.', max_length=50),
        ),
    ]
