# Generated by Django 6.0.5 on 2026-07-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotional', '0010_alter_devotionalcontent_share_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotionalcontent',
            name='daily_companion',
            field=models.TextField(blank=True, default='', help_text='A Palavra Continua: pensamento silencioso para o dia.'),
        ),
        migrations.AddField(
            model_name='devotionalcontent',
            name='main_truth',
            field=models.TextField(blank=True, default='', help_text='O Fio da Palavra: a verdade central da reflexão.'),
        ),
    ]
