# Generated by Django 6.0.5 on 2026-07-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotional', '0016_activate_all_twenty_emotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotionalcontent',
            name='anchor_text',
            field=models.TextField(blank=True, default='', help_text='Fio da Palavra'),
        ),
        migrations.AddField(
            model_name='devotionalcontent',
            name='carry_with_you_text',
            field=models.TextField(blank=True, default='', help_text='Leve com Você'),
        ),
        migrations.AddField(
            model_name='devotionalcontent',
            name='word_continues_text',
            field=models.TextField(blank=True, default='', help_text='A Palavra Continua'),
        ),
    ]
