# Generated by Django 6.0.5 on 2026-07-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotional', '0017_devotionalcontent_anchor_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotionalcontent',
            name='anchor_text',
            field=models.TextField(blank=True, default='', help_text='Fio da Palavra', verbose_name='Fio da Palavra'),
        ),
        migrations.AlterField(
            model_name='devotionalcontent',
            name='carry_with_you_text',
            field=models.TextField(blank=True, default='', help_text='Leve com Você', verbose_name='Leve com Você'),
        ),
        migrations.AlterField(
            model_name='devotionalcontent',
            name='word_continues_text',
            field=models.TextField(blank=True, default='', help_text='A Palavra Continua', verbose_name='A Palavra Continua'),
        ),
    ]
