# Generated by Django 6.0.5 on 2026-07-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotional', '0018_alter_devotionalcontent_anchor_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
