# Generated by Django 6.0.5 on 2026-05-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassageExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_normalized', models.CharField(db_index=True, max_length=100, unique=True)),
                ('reference_display', models.CharField(max_length=150)),
                ('explanation', models.TextField()),
                ('ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
