# Generated by Django 6.0.5 on 2026-05-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passageexplanation',
            name='biblical_context',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='passageexplanation',
            name='optional_prayer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='passageexplanation',
            name='practical_application',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='passageexplanation',
            name='simple_explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='passageexplanation',
            name='spiritual_reflection',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='passageexplanation',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
