# Generated by Django 6.0.5 on 2026-05-12 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_passageexplanation_biblical_context_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiblePassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('book_name', models.CharField(max_length=100)),
                ('chapter', models.IntegerField()),
                ('verses', models.CharField(blank=True, max_length=100, null=True)),
                ('text_original', models.TextField()),
                ('translation', models.CharField(default='NVI', max_length=50)),
                ('language', models.CharField(default='pt', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='passageexplanation',
            name='passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='bible.biblepassage'),
        ),
    ]
