# Generated by Django 6.0.5 on 2026-06-19 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0003_biblepassage_passageexplanation_passage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_id', models.CharField(db_index=True, max_length=100)),
                ('verse_start', models.IntegerField()),
                ('verse_end', models.IntegerField()),
                ('reference_display', models.CharField(max_length=150)),
                ('title', models.CharField(default='O foco desta leitura', max_length=100)),
                ('content', models.TextField()),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_version', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_focuses', to='bible.biblepassage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('canonical_id', 'verse_start', 'verse_end'), name='unique_reading_focus_per_range')],
            },
        ),
    ]
