# Generated by Django 6.0.5 on 2026-05-09 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('bible', 'Bible'), ('devotional', 'Devotional'), ('reflection', 'Reflection')], max_length=20)),
                ('input_hash', models.CharField(max_length=64)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('error', 'Error'), ('blocked', 'Blocked')], max_length=20)),
                ('flagged_for_review', models.BooleanField(default=False)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[('BIBLE', 'Bible'), ('DEVOTIONAL', 'Devotional'), ('REFLECTION', 'Reflection')], max_length=20)),
                ('filter_status', models.CharField(choices=[('clean', 'Clean'), ('soft_flagged', 'Soft Flagged'), ('hard_blocked', 'Hard Blocked')], max_length=20)),
                ('content_ref_id', models.PositiveIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_responses', to='ai_core.airequest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['response_type', 'content_ref_id'], name='ai_core_gen_respons_a041bd_idx'), models.Index(fields=['user', 'response_type', 'created_at'], name='ai_core_gen_user_id_5ed810_idx')],
            },
        ),
    ]
