# Generated by Django 6.0.5 on 2026-05-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequest',
            name='cache_hit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='airequest',
            name='endpoint_origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airequest',
            name='estimated_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='airequest',
            name='input_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airequest',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airequest',
            name='output_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
